### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by datomnurdin** [wildabeast/BarcodeScanner#183]
Hi, I just got an error when I try to build my project after installed this plugin.

```
BUILD FAILED
/Users/HansenFan/Penril/Tools/android-sdks/tools/ant/build.xml:653: The following error occurred while executing this line:
/Users/HansenFan/Penril/Tools/android-sdks/tools/ant/build.xml:698: null returned: 1

Total time: 2 seconds

/Users/HansenFan/Penril/workspace/UpassMobile/upass-mobile/platforms/android/cordova/node_modules/q/q.js:126
                   throw e;
                         ^
Error code 1 for command: ant with args: debug,-f,/Users/HansenFan/Penril/workspace/UpassMobile/upass-mobile/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /Users/HansenFan/Penril/workspace/UpassMobile/upass-mobile/platforms/android/cordova/build: Command failed with exit code 8
   at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
   at ChildProcess.EventEmitter.emit (events.js:98:17)
   at maybeClose (child_process.js:743:16)
   at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

Please advice. Thank you.

**Comment by kangkangding** [comment]
We also have the same problem,

-compile:
    [javac] Compiling 6 source files to D:\javawork\SmartFluxClnt2\platforms\and
roid\ant-build\classes
    [javac] ����: [options] Դֵ1.5�ѹ�ʱ, ����δ�����з��а���ɾ��
    [javac] ����: [options] Ŀ��ֵ1.5�ѹ�ʱ, ����δ�����з��а���ɾ��
    [javac] ����: [options] Ҫ�����й��ѹ�ʱѡ���ľ���, ��ʹ�� -Xlint:-options��
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:27: ����: ������com.google.zxing.client.and
roid������
    [javac] import com.google.zxing.client.android.CaptureActivity;
    [javac]                                       ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:28: ����: ������com.google.zxing.client.and
roid.encode������
    [javac] import com.google.zxing.client.android.encode.EncodeActivity;
    [javac]                                              ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:29: ����: ������com.google.zxing.client.and
roid������
    [javac] import com.google.zxing.client.android.Intents;
    [javac]                                       ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:138: ����: �Ҳ�������
    [javac]                 Intent intentScan = new Intent(that.cordova.getActiv
ity().getBaseContext(), CaptureActivity.class);
    [javac]
                        ^
    [javac]   ����: �� CaptureActivity
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:139: ����: ������Intents������
    [javac]                 intentScan.setAction(Intents.Scan.ACTION);
    [javac]                                             ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:176: ����: ������Intents������
    [javac]                         intentScan.putExtra(Intents.Scan.CAMERA_ID,
obj.optBoolean(PREFER_FRONTCAMERA, false) ? 1 : 0);
    [javac]                                                    ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:177: ����: ������Intents������
    [javac]                         intentScan.putExtra(Intents.Scan.SHOW_FLIP_C
AMERA_BUTTON, obj.optBoolean(SHOW_FLIP_CAMERA_BUTTON, false));
    [javac]                                                    ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:178: ����: ������Intents������
    [javac]                         intentScan.putExtra(Intents.Scan.SHOW_TORCH_
BUTTON, obj.optBoolean(SHOW_TORCH_BUTTON, false));
    [javac]                                                    ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:179: ����: ������Intents������
    [javac]                         intentScan.putExtra(Intents.Scan.TORCH_ON, o
bj.optBoolean(TORCH_ON, false));
    [javac]                                                    ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:181: ����: ������Intents������
    [javac]                             intentScan.putExtra(Intents.Scan.RESULT_
DISPLAY_DURATION_MS, "" + obj.optLong(RESULTDISPLAY_DURATION));
    [javac]                                                        ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:184: ����: ������Intents������
    [javac]                             intentScan.putExtra(Intents.Scan.FORMATS
, obj.optString(FORMATS));
    [javac]                                                        ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:187: ����: ������Intents������
    [javac]                             intentScan.putExtra(Intents.Scan.PROMPT_
MESSAGE, obj.optString(PROMPT));
    [javac]                                                        ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:190: ����: ������Intents������
    [javac]                             intentScan.putExtra(Intents.Scan.ORIENTA
TION_LOCK, obj.optString(ORIENTATION));
    [javac]                                                        ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:251: ����: �Ҳ�������
    [javac]         Intent intentEncode = new Intent(this.cordova.getActivity().
getBaseContext(), EncodeActivity.class);
    [javac]
                  ^
    [javac]   ����:   �� EncodeActivity
    [javac]   λ��: �� BarcodeScanner
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:252: ����: ������Intents������
    [javac]         intentEncode.setAction(Intents.Encode.ACTION);
    [javac]                                       ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:253: ����: ������Intents������
    [javac]         intentEncode.putExtra(Intents.Encode.TYPE, type);
    [javac]                                      ^
    [javac] D:\javawork\SmartFluxClnt2\platforms\android\src\com\phonegap\plugin
s\barcodescanner\BarcodeScanner.java:254: ����: ������Intents������
    [javac]         intentEncode.putExtra(Intents.Encode.DATA, data);
    [javac]                                      ^
    [javac] 17 ������
    [javac] 3 ������

BUILD FAILED
please help me ,thanks.
