### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by sid180** [wildabeast/BarcodeScanner#333]
While scanning a pdf417 barcode, app get crashed

07-26 16:44:29.579: E/AndroidRuntime(18283): FATAL EXCEPTION: Thread-6482

07-26 16:44:29.579: E/AndroidRuntime(18283): java.lang.NullPointerException: Attempt to get length of null array
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at com.google.zxing.pdf417.decoder.Decoder.decode(Decoder.java:75)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:70)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:170)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at com.google.zxing.client.android.DecodeHandler.decode(DecodeHandler.java:82)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at com.google.zxing.client.android.DecodeHandler.handleMessage(DecodeHandler.java:60)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at android.os.Looper.loop(Looper.java:145)
07-26 16:44:29.579: E/AndroidRuntime(18283): 	at com.google.zxing.client.android.DecodeThread.run(DecodeThread.java:97)

**Comment by sid180** [comment]
Hi,
I update my zxing library now working like a charm.
